/** Преподаватели: ФИО -> id в API колледжа. */
export const Teachers: Record<string, string> = {
	'Алексеева О.В.': 'alekseeva-ov',
	'Алферьева О.В.': 'alfereva-ov',
	'Апататьев Д.С.': 'apatatev-ds',
	'Бабкина В.А.': 'babkina-va',
	'Бакуменко А.А.': 'bakumenko-aa',
	'Басалаева М.В.': 'basalaeva-mv',
	'Башкирцева Е.Ю.': 'bashkirceva-eyu',
	'Белошейкин Р.В.': 'belosheykin-rv',
	'Беляева А.В.': 'belyaeva-av',
	'Беляева С.В.': 'belyaeva-sv',
	'Биц Н.А.': 'bic-na',
	'Богданов Ю.В.': 'bogdanov-yuv',
	'Боровиков Д.Л.': 'borovikov-dl',
	'Боровикова Ю.С.': 'borovikova-yus',
	'Быльцев И.А.': 'bylcev-ia',
	'Васильев Н.Г.': 'vasilev-ng',
	'Веребчан Д.Н.': 'verebchan-dn',
	'Вознюк В.В.': 'voznyuk-vv',
	'Вострецов Е.Ю.': 'vostrecov-eyu',
	'Гармаш О.С.': 'garmash-os',
	'Грищенко С.С.': 'grishchenko-ss',
	'Демин Е.А.': 'demin-ea',
	'Деревинская М.А.': 'derevinskaya-ma',
	'Додонов Ю.С.': 'dodonov-yus',
	'Докин С.Г.': 'dokin-sg',
	'Дорофеев М.С.': 'dorofeev-ms',
	'Дорофеева Е.А.': 'dorofeeva-ea',
	'Дроздова О.В.': 'drozdova-ov',
	'Дубровина Н.А.': 'dubrovina-na',
	'Дудкинская А.В.': 'dudkinskaya-av',
	'Евдокимова Е.Л.': 'evdokimova-el',
	'Еремеев А.Л.': 'eremeev-al',
	'Ермолаева А.А.': 'ermolaeva-aa',
	'Загарских К.И.': 'zagarskih-ki',
	'Земцова Н.Ю.': 'zemcova-nyu',
	'Зыков А.А.': 'zykov-aa',
	'Исаченко А.С.': 'isachenko-as',
	'Кабанов Р.А.': 'kabanov-ra',
	'Кадников М.С.': 'kadnikov-ms',
	'Кишова Н.О.': 'kishova-no',
	'Колесников Д.В.': 'kolesnikov-dv',
	Комиссия: 'komissiya',
	'Кононенко И.М.': 'kononenko-im',
	'Костенев В.И.': 'kostenev-vi',
	'Кузнецов М.Н.': 'kuznecov-mn',
	'Кузнецова С.Н.': 'kuznecova-sn',
	'Кулимин А.А.': 'kulimin-aa',
	'Култашева М.Э.': 'kultasheva-me',
	'Лебедкин Р.Н.': 'lebedkin-rn',
	'Майник Л.В.': 'maynik-lv',
	'Мандрыгина С.С.': 'mandrygina-ss',
	'Медведевских В.С.': 'medvedevskih-vs',
	'Меньков Н.А.': 'menkov-na',
	'Михайлов Г.': 'mihaylov-g',
	'Могильников С.В.': 'mogilnikov-sv',
	'Мурашко Г.Р.': 'murashko-gr',
	'Не указан': 'ne-ukazan',
	'Нечаева Т.Г.': 'nechaeva-tg',
	'Никифорова Е.Г.': 'nikiforova-eg',
	'Новикова О.В.': 'novikova-ov',
	'Норкина В.Н.': 'norkina-vn',
	'Орлов В.Б.': 'orlov-vb',
	'Павлов Ю.Н.': 'pavlov-yun',
	'Панова В.В.': 'panova-vv',
	'Парфёнов А.В.': 'parfyonov-av',
	'Петрова Д.А.': 'petrova-da',
	'Петрушина Л.А.': 'petrushina-la',
	'Подкорытова К. А.': 'podkorytova-k-a',
	'Поликарпова С.В.': 'polikarpova-sv',
	'Попов Е.В.': 'popov-ev',
	'Рассказова С.А.': 'rasskazova-sa',
	'Решанов И.С.': 'reshanov-is',
	'Рогов А.Ю.': 'rogov-ayu',
	'Рымарев В.Н.': 'rymarev-vn',
	'Сердюк В.В.': 'serdyuk-vv',
	'Сердюк Н.П.': 'serdyuk-np',
	'Синцова С.Г.': 'sincova-sg',
	'Скальская Н.В.': 'skalskaya-nv',
	'Скоморохова Е.А.': 'skomorohova-ea',
	'Сметанина Д.В.': 'smetanina-dv',
	'Соколов Г.К.': 'sokolov-gk',
	'Соколова Н.Г.': 'sokolova-ng',
	'Стефанович Ю.Г.': 'stefanovich-yug',
	'Сутягина Л.Н.': 'sutyagina-ln',
	'Сухачева А.Р.': 'suhacheva-ar',
	'Сюткин Д.М.': 'syutkin-dm',
	'Терентьева О.А.': 'terenteva-oa',
	'Тимиргазин М.М.': 'timirgazin-mm',
	'Тимошинова Л.П.': 'timoshinova-lp',
	'Титова К.С.': 'titova-ks',
	'Тоторина М.А.': 'totorina-ma',
	'Трофимова А.И.': 'trofimova-ai',
	'Тыщенко Е.В.': 'tyshchenko-ev',
	'Уткина Э.М.': 'utkina-em',
	'Филимонов В.И.': 'filimonov-vi',
	'Фомин И.А.': 'fomin-ia',
	'Фурс Т.В.': 'furs-tv',
	'Хамматова Л.М.': 'hammatova-lm',
	'Холкин Д.А.': 'holkin-da',
	'Черняева И.А.': 'chernyaeva-ia',
	'Чукреева С.Э.': 'chukreeva-se',
	'Чуркин А.В.': 'churkin-av',
	'Шабунина О.С.': 'shabunina-os',
	'Шайтанова О.Н.': 'shaytanova-on',
	'Шамшеев В.А.': 'shamsheev-va',
	'Шестаков А.А.': 'shestakov-aa',
	'Шефер Е.В.': 'shefer-ev',
	'Ширяев М.В.': 'shiryaev-mv',
	'Шутова Н.Н.': 'shutova-nn',
	'Южанинова Т.А.': 'yuzhaninova-ta',
};

export const TeacherList: [string, string][] = Object.entries(Teachers);

export const TeacherNameById: Record<string, string> = Object.fromEntries(
	TeacherList.map(([name, id]) => [id, name]),
);

/** Поиск преподавателей по части ФИО (регистр не важен). */
export function searchTeachers(query: string, limit = 20): [string, string][] {
	const needle = query.trim().toLowerCase();
	if (!needle) return [];
	return TeacherList.filter(([name]) => name.toLowerCase().includes(needle)).slice(0, limit);
}
